### ISSUE TITLE
Loader Does Not Successfully Reset CPU After Flash

### ISSUE THREAD

**Issue by stieg** [autosportlabs/ASL_F4_bootloader#12]
Upon flashing the unit the loader will not successfully reset the CPU back into the newly flashed code.  Instead it gets stuck someplace.  How to reproduce:
1. Plug in rct/mk2, and ensure you can talk to it in Minicom
2. Flash any version of 2.10.0 or 2.9.x firmware

Notice that the unit does not reset properly after flash.  Firmware seems to handle this well.

**Comment by Jeff-Ciesielski** [comment]
Does a power cycle bring the unit to a working state?

In any event, I"ll take a look this weekend.

**Comment by stieg** [comment]
A power cycle does fix the issue

**Comment by Jeff-Ciesielski** [comment]
Dug into this a bit last night.  What appears to be happening is that the loader successfully writes the image, however it cannot seem to validate the image CRC.  Will continue digging to figure out what the root of this is.

**Comment by stieg** [comment]
@Jeff-Ciesielski 's fix combined with https://github.com/autosportlabs/RaceCapture-Pro_firmware/pull/774 seem to have resolved the issue.  Closing
